name: Docker CI with Tags

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        id: get_version
        run: |
          # If this is a tag, use the tag name
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=latest
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            medisimo/cicd-pipeline:${{ steps.get_version.outputs.VERSION }}
            medisimo/cicd-pipeline:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/cicd-project
            sudo docker stop nodejs-app || true
            sudo docker rm nodejs-app || true
            sudo docker pull medisimo/cicd-pipeline:${{ steps.get_version.outputs.VERSION }}
            sudo docker run -d \
              --name nodejs-app \
              -p 3000:3000 \
              medisimo/cicd-pipeline:${{ steps.get_version.outputs.VERSION }}
