name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: medisimo/cicd-pipeline:latest
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/cicd-project
          sudo docker stop nodejs-app || true
          sudo docker rm nodejs-app || true
          sudo docker rmi medisimo/cicd-pipeline:latest || true
          sudo docker pull medisimo/cicd-pipeline:latest
          sudo docker run -d \
            --name nodejs-app \
            -p 3000:3000 \
            medisimo/cicd-pipeline:latest
