name: Docker CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' 
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run tests
        run: npm test

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=latest
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            medisimo/cicd-pipeline:${{ steps.get_version.outputs.VERSION }}
            medisimo/cicd-pipeline:latest

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH key format
        run: |
          echo "Checking SSH key format..."
          echo "${{ secrets.EC2_SSH_KEY }}" | grep -q "BEGIN" && \
          echo "SSH key starts correctly" || echo "SSH key may be malformed"
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 60s
          script: |
            docker pull medisimo/cicd-pipeline:latest
            docker stop cicd-container || true
            docker rm cicd-container || true
            docker run -d --name cicd-container -p 3000:3000 medisimo/cicd-pipeline:latest
